# Generated by Django 4.0 on 2021-12-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=20, unique=True)),
                ('Color', models.CharField(max_length=30)),
                ('JAN_Code', models.IntegerField(unique=True)),
                ('Image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
