# Generated by Django 4.0 on 2021-12-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobilemodel',
            new_name='mobile_model',
        ),
    ]
