# Generated by Django 4.0 on 2021-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_rename_mobilemodel_mobile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_model',
            name='Image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='mobile_model',
            name='Model',
            field=models.CharField(max_length=20),
        ),
    ]
