# Generated by Django 4.0 on 2021-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_alter_mobile_model_image_alter_mobile_model_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_model',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
